# Generated by Django 3.2.25 on 2024-08-29 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(default='', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(default='', max_length=128)),
                ('post_no', models.IntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_profiles', to='authentication.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FollowersKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relationships', to='authentication.userprofile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='authentication.userprofile')),
            ],
            options={
                'unique_together': {('user_id', 'following_user_id')},
            },
        ),
    ]
