# Generated by Django 3.2.25 on 2024-08-24 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(default='', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(default='', max_length=128)),
                ('post_no', models.IntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_profiles', to='authentication.UserProfile')),
            ],
        ),
    ]
