# Generated by Django 3.2.25 on 2024-08-23 03:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240822_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_user_ids',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
